### ISSUE TITLE
Badge proposal: Sledge hammer - Accepted

### ISSUE THREAD

**Issue by mjbakker** [DealerDirect/Achievements#125]
A Sledge Hammer badge for heavy impact, positive or negative.

Can I get a vote yay/nay for all of those eligible to vote?

| Developer | Yay | Nay |
| --- | --- | --- |
| @arjank | :ballot_box_with_check: | |
| @Dravenshorst | :ballot_box_with_check: | |
| @eaulav | :ballot_box_with_check: | |
| @edvance | |  |
| @Marascon | :ballot_box_with_check: | |
| @mjbakker |:ballot_box_with_check: |  | 
| @pimkaptein | :ballot_box_with_check:  | |
| @potherca | :ballot_box_with_check: | |
| @wouteroostervld | | |
| **Auxiliary Developer** | **Yay** | **Nay** |
| @hipio | :ballot_box_with_check: | |
| Total = 9 (+1)| 6 (+1) | 0 |

**Comment by hipio** [comment]
Yay 👍

**Comment by Potherca** [comment]
:+1:

**Comment by arjank** [comment]
:+1:

**Comment by mjbakker** [comment]
![6tyoja8lc](https://cloud.githubusercontent.com/assets/21199050/18706487/7db10fda-7ff2-11e6-866a-f05d0c06211b.jpg)
 Looks like we are going to have a new badge soon. Yay

**Comment by Dravenshorst** [comment]
:+1:

**Comment by Potherca** [comment]
Proposed over a week ago. Those who have not yet responded are out of luck.

Marking this as approved.

**Comment by Potherca** [comment]
Accepting PRs for this.

@frankyxl Can we bother you for a nice design? :smile_cat:

**Comment by Potherca** [comment]
Fixed by #154.
