### ISSUE TITLE
Badge proposal: Education - Accepted

### ISSUE THREAD

**Issue by frenck** [DealerDirect/Achievements#148]
An Education badge for educating colleagues

Can I get a vote yay/nay for all of those eligible to vote?

| Developer | Yay | Nay |
| --- | --- | --- |
| @arjank | | |
| @Dravenshorst | :ballot_box_with_check: | |
| @eaulav | | |
| @edvance | :ballot_box_with_check: | |
| @frenck | :ballot_box_with_check: | |
| @Marascon | :ballot_box_with_check: | |
| @mjbakker |:ballot_box_with_check: | | 
| @pimkaptein | | |
| @potherca | :ballot_box_with_check: | |
| @wouteroostervld | | |
| **Auxiliary Developer** | **Yay** | **Nay** |
| @hipio | :ballot_box_with_check: | |
| Total = 10 (+1)| 6 (+1) | 0 |

![Education](http://fantasyscotus.org/wp-content/uploads/2011/12/education1.png)

**Comment by hipio** [comment]
Yay

**Comment by Dravenshorst** [comment]
:+1:

**Comment by Marascon** [comment]
Yay!

**Comment by edvance** [comment]
Yay!

**Comment by Potherca** [comment]
Yay.

@frankyxl Can you create a design for this?

**Comment by mjbakker** [comment]
Yay!

**Comment by arjank** [comment]
Yay!

**Comment by frankyxl** [comment]
bestaat al :)!

**Comment by Potherca** [comment]
Due to overwhelming support for this a PR has already been accepted.

Fixed in #154
