### ISSUE TITLE
Chrome Issue: Badges are no longer grayed out if unawarded

### ISSUE THREAD

**Issue by hipio** [DealerDirect/Achievements#159]
Badges used to be gray when you didn't have them. This is broken since the latest Google Chrome update with this error message:

```Unsafe attempt to load URL data:image/svg+xml;utf8,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' height='0'><filter id='greyscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0' /></filter></svg>#greyscale from frame with URL https://dealerdirect.github.io/Achievements/profiles/franck-nijhof/. Domains, protocols and ports must match.```

**Comment by Potherca** [comment]
Related: http://stackoverflow.com/questions/39646388/xmlns-w3-url-for-svg-spec-now-throwing-error-in-chrome
