### ISSUE TITLE
Automatic reset at end of sprint

### ISSUE THREAD

**Issue by Marascon** [DealerDirect/Achievements#27]
Yes, we need this.

**Comment by Potherca** [comment]
Any suggestions on how to achieve that? It might be easier to add a simple (ruby) script that gathers all of the usernames and overwrites their score files with the data from the `empty.yml` file.

A developer would still have to commit/push those changes but it would take some of the manual labour out of the process...

**Comment by Marascon** [comment]
This was exactly my idea but basicly with a simple bash script that does a copy.
