### ISSUE TITLE
Badge Proposal: KAK - Accepted

### ISSUE THREAD

**Issue by frenck** [DealerDirect/Achievements#86]
I would like to propose a new badge: [KAK](https://www.google.nl/search?q=kak&safe=off&biw=2537&bih=1554&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjP-t6LjNrOAhXmIcAKHRQ-DAIQ_AUIBigB#safe=off&tbm=isch&q=kaka+drol).

It doesn't happen _often_ (except maybe me...) but it would be nice to be able to award a person a badge when he uses the word or does something shitty.

Badge image:

![KAK](https://s3.amazonaws.com/uploads.hipchat.com/617086%2F4247586%2FCfJ9v1TgyTATVsV%2Fpoo_thumb.png)

Can I get a vote yay/nay for all of those eligible to vote?

| Developer | Yay | Nay |
| --- | --- | --- |
| @arjank | :ballot_box_with_check: | |
| @Dravenshorst | :ballot_box_with_check: | |
| @eaulav | :ballot_box_with_check: | |
| @edvance | :ballot_box_with_check: | |
| @Marascon | :ballot_box_with_check: | |
| @mjbakker | :ballot_box_with_check: | | 
| @pimkaptein | :ballot_box_with_check: | |
| @potherca | :ballot_box_with_check:  | |
| @wouteroostervld | :ballot_box_with_check: | |
 Total = 9 | 9 | 0 |

**Comment by Marascon** [comment]
i wholeKAKKINGLY approve of this,

**Comment by Potherca** [comment]
:+1:

**Comment by eaulav** [comment]
👍

**Comment by pimkaptein** [comment]
Is it going to be a negative or a positive one?

**Comment by edvance** [comment]
Yay

**Comment by wouteroostervld** [comment]
Beetje viezige batch, maar ok dan. Yay!

**Comment by Dravenshorst** [comment]
:+1:

**Comment by mjbakker** [comment]
Positive -:)

**Comment by Potherca** [comment]
All are in favour. This badge has been voted in. A PR adding this badge to the repository will now be accepted.

**Comment by Potherca** [comment]
Closed by #106.
