### ISSUE TITLE
Badge proposal: Mand! (basket) - Declined

### ISSUE THREAD

**Issue by eaulav** [DealerDirect/Achievements#99]
Basket badge for saying something very short and clear, for more information on why this needs to be a Basket:

[Youtube](https://youtu.be/ypSKDY4Jp3g)

Can I get a vote yay/nay for all of those eligible to vote?

| Developer | Yay | Nay |
| --- | --- | --- |
| @arjank | | |
| @Dravenshorst | :ballot_box_with_check: | |
| @eaulav | :ballot_box_with_check: | |
| @edvance | | :ballot_box_with_check: |
| @Marascon | :ballot_box_with_check: | |
| @mjbakker | | :ballot_box_with_check: | 
| @pimkaptein | | :ballot_box_with_check: |
| @potherca | | :ballot_box_with_check: |
| @wouteroostervld | | |
 Total = 9 | 3 | 4 |

**Comment by Dravenshorst** [comment]
:+1:

**Comment by Potherca** [comment]
Itis not entirely clear to me what this badge adds that cannot be addressed by current badges... I am also slightly concerned that people will award this as "basket case". That may, however, not be a bad thing as the "crack pipe" badge has been veto'd as too NSFW.

**Comment by frenck** [comment]
Not sure about this one...

**Comment by Potherca** [comment]
Shorter.

**Comment by Marascon** [comment]
Got my stamp of approval.

**Comment by mjbakker** [comment]
Nah, I don't think it's a good one.

**Comment by Potherca** [comment]
I am also going to "nay" this one.

**Comment by edvance** [comment]
nay too, and better try some names which have a less arbitrary meaning so
people don't have to think that 'much' about what it means, like for
example "zak hooi".

**Comment by Potherca** [comment]
This proposal is not gathering enough support.

Closing as Declined.
